# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_experience_end_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
