# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
        ('experience', '0003_experience_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='seeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seeker.Seeker'),
            preserve_default=False,
        ),
    ]
