# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('web_url', models.CharField(blank=True, max_length=500, null=True)),
                ('job_description', models.TextField()),
                ('job_title', models.CharField(max_length=500)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Other', 'Other')], default='Other', max_length=100)),
            ],
            options={
                'db_table': 'employer',
            },
        ),
    ]
