version: '3'

services:
  db:
    image: postgres:9.5
    volumes:
        - 'db:/var/lib/postgresql/data'
    env_file:
      - '.env'
    ports:
        - '5432:5432'

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - '.env'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db: