# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
        ('jobs', '0002_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(to='seeker.Seeker'),
        ),
    ]
